language: go

go:
  - 1.9

install:
  - go get -u github.com/golang/dep/...
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - dep ensure

script:
  - make test

after_success:
  - make cover
